### ISSUE TITLE
Info page about a committee shows previous members as well

### ISSUE THREAD

**Issue by edvardvb** [webkom/lego-webapp#1041]
The list does not take the role of the membership into account.

**Comment by SmithPeder** [comment]
Can you elaborate on this. Do you refer to these pages?
https://abakus.no/pages/komiteer/11
I dont know about the other committees, but Webkoms looks up to date

**Comment by edvardvb** [comment]
Yeah, see Arrkom as an example:
https://abakus.no/admin/groups/4/members
https://abakus.no/pages/komiteer/4

Memberships listed as Pang or Aktiv Pang show up in the list of members, which is not intended.
