### ISSUE TITLE
Navigation autocomplete search should display and sort by date

### ISSUE THREAD

**Issue by finnss** [webkom/lego-webapp#1045]
Right now searching for "Bekk" yields a bunch of results with no indication of whether it's an event from 4 years ago, the company's page, or some other content. A first step to solve this should be to display the most recent first, as that's likely the most relevant. That information should also be visible to the user. 

This sorting should be done back-end because of pagination, and if the date isn't already being sent then that needs to be added to the serializer as well.

**Comment by odinuge** [comment]
This is partly solved by #1063, and will be further improved with better search results :smile:
