### ISSUE TITLE
Weird event start time

### ISSUE THREAD

**Issue by ekmartin** [webkom/lego-webapp#1051]
From https://abakus.no/events/2145: 

![image](https://user-images.githubusercontent.com/3536982/35100517-6928f158-fc5c-11e7-9251-0064be1d0898.png)

Should've been 12:00 (and the API shows `2018-01-18T11:00:00Z` as the activation date). `new Date()` in the Chrome console returns `Thu Jan 18 2018 14:33:00 GMT+0100 (CET)` - so probably not a timezone issue?

This also affects the registration box:
![image](https://user-images.githubusercontent.com/3536982/35100636-c47ca1ee-fc5c-11e7-9fcd-7fecc9a2356b.png)

**Comment by odinuge** [comment]
This looks like a real world example of #1010, or I am wrong? Looks like ypu have 2 penalties, resulting in a 12h reg. delay.

**Comment by ekmartin** [comment]
Ahhhh, that's probably it! Oops. I'll check when I get home.
