### ISSUE TITLE
Title of penalty section

### ISSUE THREAD

**Issue by odinuge** [webkom/lego-webapp#1070]
The title of the penalty section in user details should not display `Du har ...` for other user than the current logged in user. It should instead say something like `Brukeren har ...` for other users.
![screenshot from 2018-01-27 16-59-05](https://user-images.githubusercontent.com/1467188/35473629-874ddbf2-0383-11e8-9394-3883768978ba.png)

**Comment by ekmartin** [comment]
Does it really need a sentence at all? Is it confusing if it just says `1 prikk` for everyone that sees it?

**Comment by odinuge** [comment]
Yeah, fair point 😂
