### ISSUE TITLE
Update event detail for new permission system

### ISSUE THREAD

**Issue by edvardvb** [webkom/lego-webapp#1096]
Depends on this: https://github.com/webkom/lego/pull/1027

- Remove login-requirement on both detail and list
- Make the detail view pretty when not showing registrations
  - Show number of registrations in each pool, but not users (also waiting regs)
  - Show "login to register" when needed
  - Hide all components about registered users (icons, lists of registered users etc)
- Add is_abakom_only checkbox in editor

**Comment by odinuge** [comment]
Werkz

![screenshot from 2018-02-06 00-53-04](https://user-images.githubusercontent.com/1467188/35834939-3c1b03ba-0ad8-11e8-9a2c-e0f0dcea7d17.png)

Bare nånn småting som mangle
