### ISSUE TITLE
Random users receive Event.SOCKET_REGISTRATION.SUCCESS from other users

### ISSUE THREAD

**Issue by santi** [webkom/lego-webapp#1101]
Randomly got this event when monitoring Redux state on the live website:
![registration-event](https://user-images.githubusercontent.com/8686628/36021813-4ab9cae4-0d87-11e8-802f-0cc19d7c25c7.png)

**Comment by hanswilw** [comment]
It is websockets that updates the state which is used for the registration counters in the event list and calendar - as well as detailed events. This is by intention 👍🏻
