### ISSUE TITLE
Committee "about us" pages have no text for non-admin users

### ISSUE THREAD

**Issue by edvardvb** [webkom/lego-webapp#1118]
https://abakus.no/pages/komiteer/11 will show logo and member list, but not info text for regular users

**Comment by odinuge** [comment]
Ahaha,

This is a serializer/permission _problem_. https://github.com/webkom/lego/blob/master/lego/apps/users/serializers/abakus_groups.py#L33. The same does indeed happen with interestgroups. We already provide the `description` to all groups, so providing the `text`-value shouldn't be a problem.

Maybe we should create a new serializer for `retrive` for interestgroups and committees?

**Comment by odinuge** [comment]
![screenshot from 2018-02-15 12-52-45](https://user-images.githubusercontent.com/1467188/36255397-26e13c34-124f-11e8-99a1-13b72ddfcf22.png)

**Comment by odinuge** [comment]
Solved in https://github.com/webkom/lego/pull/1098
