### ISSUE TITLE
Editor guide

### ISSUE THREAD

**Issue by ekmartin** [webkom/lego-webapp#1137]
Could have a page that explains tips and tricks about the editor, and link to it with a sentence wherever the editor is used. 

Lots of hotkeys here: https://github.com/brijeshb42/medium-draft

**Comment by finnss** [comment]
Could use some expanding, but not at least exists https://abakus.no/articles/125

**Comment by finnss** [comment]
It's not automatically linked to wherever the editor is used though, that seems like an important aspect of the feature
