### ISSUE TITLE
Gallery issues

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#1155]
- [x] Action Grants for both list, pictures and so forth

- [x] Navigation when you view a image. Both with arrow-keys and with buttons

- [x] Sort albums by date 

- [x] Pagination error album list

- [x] Add "confirm delete" modal

- [ ] Make a better highlight of what pictures are public and not (edit). Maybe add a filter too?

- [ ] Add a not to edit view about hiding pictures. Hidden pictures are only visible for people with edit access to the gallery.

- [x] Edit gallery title is currently "Nytt album"

**Comment by mrfarstad** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/2e29187e-812d-4803-bdec-9e49ef28a2d5-ddbe6452-5767-4bdf-8a07-6750a1523753-v1.png?transparent=1&palette=1&width=246)

**Comment by mrfarstad** [comment]
Sorting albums by date: Do we want the albums to be sorted by the date it was taken or the date when the album was created?

- It is now currently sorted by when it was taken and not when it was created.

- It is a bit risky to sort on when it was taken, as this field can be null in the back end. Therefore, there might be several previously created albums with null values for this field.

**Comment by odinuge** [comment]
Gallery pagination was fixed in https://github.com/webkom/lego-webapp/commit/59974743b81746946ebfef01079cc69b54fc7b15

**Comment by mrfarstad** [comment]
- Action grants for both list, pictures and so forth
- Add "confirm delete" modal

Solved in #1182. :100:

**Comment by finnss** [comment]
Anything still unsolved here? @odinuge @mrfarstad @SmithPeder

**Comment by SmithPeder** [comment]
Closing this
