### ISSUE TITLE
Can only hide two pictures at a time?

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#1159]
One of PR members said she could only hide two pictures at a time?

**Comment by odinuge** [comment]
This may be a misunderstanding:

If you select pictures that are both `visible` and `hidden`, you can't click `make public`/`make private`.

![screenshot from 2018-04-01 16-13-00](https://user-images.githubusercontent.com/1467188/38174060-a1317878-35c7-11e8-8adb-3585e88b8e6c.png)

Maybe we should highlight the visibility of pictures better? Eg. show an icon on only hidden pictures??
