### ISSUE TITLE
Going to the same (answered) survey twice [As normal user]

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#1164]
It creates a toast, but it looks like you can answer the survey again.
- You cant answer twice, it gives a new toast when you try to send in a new answer

![screenshot from 2018-03-12 18-21-03](https://user-images.githubusercontent.com/23152018/37299085-920da2d6-2622-11e8-9685-5ab2e6deed7e.png)

**Comment by finnss** [comment]
This is a permissions issue backend, will fix
