### ISSUE TITLE
Mega issue for survey creation

### ISSUE THREAD

**Issue by edvardvb** [webkom/lego-webapp#1165]
- [x] Title error message is all caps
- [x] Prefilling title with template name could be misleading
- [x] Placeholder for event field could be misleading, replace with `Enter event here...`
- [x] No way of deleting alternatives, no intuitive way of seeing that empty alternatives are allowed
- [x] Looks like you can click the radio buttons and check boxes when creating
- [ ] Text box for free text questions looks like you can write in it 
- [x] #1164 
- [x]  Creating duplicate surveys gives `This filed must be unique`
  - Agreed that a redirect to the existing survey would be a good solution
- [ ]  Poor error message after creating a new survey for an event, after deleting the previous survey

**Comment by SmithPeder** [comment]
Outdated survey issue. Migrate to https://github.com/webkom/lego-webapp/issues/1321
