### ISSUE TITLE
"My surveys" page

### ISSUE THREAD

**Issue by finnss** [webkom/lego-webapp#1170]
We should have a page where bedkom and fagkom can see the surveys they've made. After that, I would also like a page where regular users can see all surveys they've answered, plus any they have yet to answer in big highlighted text. Both of these would probably include some backend changes.

I imagine the following: In the list view, instead of the current "Liste" menu item, instead have one called "Alle" (if you're sudo) and one called "Mine". In the latter, add a checkbox that's only visible for sudo users where they can select "Show surveys I've made" and/or "Show surveys I've answered".

**Comment by SmithPeder** [comment]
Closed due to https://github.com/webkom/lego-webapp/issues/1321
