### ISSUE TITLE
Shift+Enter should be the same as Enter in Editor

### ISSUE THREAD

**Issue by finnss** [webkom/lego-webapp#1227]
Atm Shift+Enter looks like it provides a small line break but it doesn't when you save. Some people use shift enter to make sure Enter doesnt trigger Save, so the functionality should be the same.

https://github.com/brijeshb42/medium-draft/blob/afa8fe40b4dfb738dd00076e6c32d458b20b6270/src/editor.js#L49

https://github.com/brijeshb42/medium-draft/blob/afa8fe40b4dfb738dd00076e6c32d458b20b6270/src/util/keybinding.js

**Comment by odinuge** [comment]
Solved in https://github.com/webkom/lego/pull/1229 :tada:
