### ISSUE TITLE
Quote action changes surveys redux-state

### ISSUE THREAD

**Issue by odinuge** [webkom/lego-webapp#1230]
When clicking "Tilfeldig sitat" inside a survey result page `https://abakus.no/surveys/{pk}/submissions/summary`, the page rerenders because the `survey` state is changed by the quote action.

![screenshot from 2018-04-24 23-19-20](https://user-images.githubusercontent.com/1467188/39214812-068c8842-4816-11e8-8cf3-bd7a03d5068d.png)

**Comment by odinuge** [comment]
Edit: may be because of this in place `sort` on each render: https://github.com/webkom/lego-webapp/blob/master/app/routes/surveys/components/Submissions/SubmissionSummary.js#L95

**Comment by mrfarstad** [comment]
@odinuge is this still an issue? 
<img width="554" alt="screenshot 2018-10-31 at 21 09 58" src="https://user-images.githubusercontent.com/22096331/47815697-5ac8d200-dd51-11e8-835b-29b7397f505a.png">
Seems to be working properly now, idk what commit changed it though
