### ISSUE TITLE
Ønsker memestøtte i møteinnkalling

### ISSUE THREAD

**Issue by andrinelo** [webkom/lego-webapp#1245]
Oppdaget akkurat at Abakus har møteinnkalling, hehe dette har gått meg hus forbi, men jeg vil gjerne ta det i bruk. Vi sender ut ukens meme i hver møteinnkalling, men møteinnkallingen har ikke støtte for meme meme meme meme 💯

**Comment by SmithPeder** [comment]
REEEEEEEEEEEEEEEEEEEEEEE

**Comment by andrinelo** [comment]
:(
