### ISSUE TITLE
Company Interest: Add label tags to text next to checkboxes

### ISSUE THREAD

**Issue by cherrybeans** [webkom/lego-webapp#1261]
Now you can only choose box by clicking on the box, but you should be able to click on the text to select it.

**Comment by SmithPeder** [comment]
@odinuge Why aren't these Issues closing on their own :cry:  My last two PR had "Fix" and "Fixes" which are both in the github allowed list :-1: 
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
