### ISSUE TITLE
Overhaul welcome page when not logged in

### ISSUE THREAD

**Issue by cherrybeans** [webkom/lego-webapp#1275]

**Comment by SmithPeder** [comment]
How about something like this? 

![screenshot from 2018-09-06 02-09-06](https://user-images.githubusercontent.com/23152018/45127706-e2db9280-b179-11e8-917b-b6b4c488e7f4.png)
![screenshot from 2018-09-06 02-06-31](https://user-images.githubusercontent.com/23152018/45127707-e4a55600-b179-11e8-8231-c520b9f7242c.png)
