### ISSUE TITLE
Fields are required in survey which appear not to be required

### ISSUE THREAD

**Issue by mrfarstad** [webkom/lego-webapp#1279]
When filling out a new survey, some fields are marked as required. I just ran into a bug where I had to fill out all the fields, regardless if they were marked as required.

**Comment by cherrybeans** [comment]
Know of a few more reports of this. Worked fine on refresh though.

**Comment by odinuge** [comment]
Fixed in https://github.com/webkom/lego-webapp/commit/ec367e50532450f1c53d02c39f0937631c268f13
