### ISSUE TITLE
Events with active sign-ups should be more visible

### ISSUE THREAD

**Issue by estensen** [webkom/lego-webapp#1296]
When navigating to abakus.no I want to right away see which events I can sign up for or soon will be.
Sometimes the lists on the frontpage is occupied by other events so I have to navigate to `/events`. And then you have to remember which event you were signing up for.

**Comment by SmithPeder** [comment]
We could not agree more. We just merged https://github.com/webkom/lego/pull/1285 which should solve the back-end part of this issue. I just have to write some quick cases for the front-end and this should look pretty good. Each events will have `opens in (x)` if the registration is still closed.

**Comment by SmithPeder** [comment]
I'll close this as I think the implementation of #1397 and #1412 will suffice
