### ISSUE TITLE
As a user I want to see the next month instead of the beginning of the current month

### ISSUE THREAD

**Issue by HoboKristian** [webkom/lego-webapp#1299]
It is not as prevalent atm since it is the 10. but I was thinking about this towards the end of September.

With the current implementation the default calender-view shows you e.q. the entirety of October when it is 27.10. However, it would be better to see the last week of October and ~4 weeks into November. Similar to how Calendar on Mac works with a scrolling calender instead of a paginated one.

 
<img width="1268" alt="screen shot 2018-10-10 at 11 07 50" src="https://user-images.githubusercontent.com/843919/46725605-d072de00-cc7c-11e8-9eeb-15925f70267c.png">

**Comment by SmithPeder** [comment]
We fixed  https://github.com/webkom/lego-webapp/issues/1298 with https://github.com/webkom/lego-webapp/pull/1310 and I think the majority want to view the current month.

If you still want this we are open to a PR where you implement the proposed, so users can switch between the two types of views through navigation.
