### ISSUE TITLE
Notification shows multiple invitations

### ISSUE THREAD

**Issue by vhellem** [webkom/lego-webapp#1308]
Not sure if frontend or backend issue. 

<img width="370" alt="screen shot 2018-10-17 at 11 10 25" src="https://user-images.githubusercontent.com/9450684/47075725-68cd0d80-d1fd-11e8-9e63-33b12f8c3fd2.png">

When getting a notification for invitation, it shows 2 or 3 invitations for each single invitation.

**Comment by odinuge** [comment]
Hi!

This was fixed in https://github.com/webkom/lego/pull/1363, and should be running in production now :tada:
