### ISSUE TITLE
Brand Guidelines

### ISSUE THREAD

**Issue by estensen** [webkom/lego-webapp#1326]
Sometimes people use the wrong colors, a compressed version of our logo or mangles it in a way that we in PR do not approve of.

It would be awesome to have a static page with brand guidelines like [Slack](https://slack.com/brand-guidelines) has. This way everyone would have access to it without needing access to our Wiki. We can also refer third-parties to this page.

I would be more than happy to help implement this.

**Comment by SmithPeder** [comment]
I can create `abakus.no/brand-styleguides` or `abakus.no/style-guidelines` and fix the basic routing for the page, then you guys can fill it with whatever you want. Just a static page like that should be nice and easy.
