### ISSUE TITLE
Podcasts issues

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#1331]
Sooo `abakus/podcasts` is running in prod, and seem to be semi-functional...
Please add things to this list if you find something that isn't working.

- [x] Need to add delete modal.

- [x] Editing a podcast gives the wrong toast.

- [x] Editing a podcast actually just creates a new podcast (hence the wrong toast).

- [x] Sometimes when you delete a podcast the mutation doesn't happen so you have to refresh.

- [ ] There should be some sort of validation on the SoundCloud link when you submit.

- [ ] There should be some sort of validation to check if the podcast is a duplicate.

- [x] The mobile view could use some tweaking.

- [ ] z-index not might be over some modals

- [x] Show real-time date from API

- [x] Show real-time views from API

- [ ] Loading indicator when `track` is undefined, this will fix the "Edit wrong link" when loading

**Comment by orhanhenrik** [comment]
Would be awesome to have the progress of listening synced to your user, so if you go back it remembers what you have listened to and how far along you were.

**Comment by SmithPeder** [comment]
Going to Mars would also be cool, but and the probability of that happening is greater than this ever happening.

**Comment by SmithPeder** [comment]
Works fine for now. I might do some changes as they have their podcasts on Spotify as well and I wanna play with that web player/API
