### ISSUE TITLE
Template and Example "pengesøknad" does not link to the resource

### ISSUE THREAD

**Issue by HoboKristian** [webkom/lego-webapp#1340]
https://abakus.no/pages/info/39-praktisk-informasjon

Under "Forslag til mal:" the two next sentences should be links (at least I assume so) to a resource:
Mal til pengesøknad
Eksempel på utfylt søknad

**Comment by cherrybeans** [comment]
Filene ble funnet på gamle NERD, lastet opp på drive og linket fikset!
