### ISSUE TITLE
Both sections are selected at the same time

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#1356]
At https://abakus.no/quotes/ , if one goes to to the unapproved section both sections will look selected
<img width="407" alt="screenshot 2018-11-01 at 18 09 32" src="https://user-images.githubusercontent.com/23152018/47867277-5f4cc380-de01-11e8-896a-f9bf1475638e.png">

**Comment by fireflower1** [comment]
Close due to #1377
