### ISSUE TITLE
Fix timeout issues on server-side rendering

### ISSUE THREAD

**Issue by ekmartin** [webkom/lego-webapp#546]
E.g. https://webapp.abakus.no/meetings/fadsfasdfasdf returns:

![image](https://user-images.githubusercontent.com/3536982/30640028-9026642a-9e01-11e7-8db8-b48dd2f8c67a.png)

**Comment by odinuge** [comment]
Monkeypatched in #877. :monkey: 

Fixed in #920 :fireworks: :tada: :1st_place_medal: :+1: :fire: :file_cabinet: :package: :computer:
