### ISSUE TITLE
Search result information and ranking

### ISSUE THREAD

**Issue by Hanse** [webkom/lego-webapp#749]
When searching for example "Itera", you get a list with a bunch of items saying only "Itera". Some of these are company presentations but the first result one seems to be the earliest one (in 2013).

Would be nice to add some more details in the result list and change the result ranking/ordering.

**Comment by odinuge** [comment]
Solved by @JonasBak in #1063 

![screenshot from 2018-02-20 12-57-56](https://user-images.githubusercontent.com/1467188/36422759-c1c719c0-163d-11e8-81c3-23e76c7a2138.png)
