### ISSUE TITLE
Find space for Bekk logo 🙃

### ISSUE THREAD

**Issue by edvardvb** [webkom/lego-webapp#788]

**Comment by SmithPeder** [comment]
Just a suggestion but the footer is a natural place for sponsors/ads/partners - and so forth
Applying their logo on every page might be overkill, but its nice to them at least 
![screenshot from 2017-10-26 21-38-58](https://user-images.githubusercontent.com/23152018/32073370-1d1f816c-ba96-11e7-8854-f651c58e3503.png)

**Comment by edvardvb** [comment]
I'd like to have it in the footer as well, but I don't think the text is necessary. Also, any text placed next to their logo is automatically associated with them, which might not be a good thing :confused:
