### ISSUE TITLE
Mark notifications as read when users open the notification box

### ISSUE THREAD

**Issue by ekmartin** [webkom/lego-webapp#832]
Slightly opinionated, but I think having a mark all as read button is kind of unnecessary.

**Comment by edvardvb** [comment]
I think it's nice to be able to "snooze" notifications for later by simply not removing them. Maybe it's possible to mark them as read by opening, and to remove them completely by clicking a button in the dropdown?

**Comment by ekmartin** [comment]
Yeah, with some websites I'd agree, I just don't know if any of the notifications we have are important enough for snoozing? Maybe I just don't use it as actively as I could.

I think in general we should remove links to names and stuff though and just do something similar to Facebook notifications instead, where the whole notification links to e.g. the comment its about, the event, the meeting etc.

**Comment by edvardvb** [comment]
Heh, turns out we already support what I was talking about. If I open my notifications now I still get the list of old notifications.
