### ISSUE TITLE
Feed content is sometimes empty

### ISSUE THREAD

**Issue by ekmartin** [webkom/lego-webapp#833]
Looks like it doesn't work with server side rendering.

**Comment by odinuge** [comment]
I think this was a result of `replaceUnlessLoggedIn` eating the `loggedIn` prop. ref. https://github.com/webkom/lego-webapp/pull/835.

Looks like this works well in `PROD` now. You can double-check before closing @ekmartin.

**Comment by ekmartin** [comment]
yep, looks good!
