### ISSUE TITLE
The menu and search button has the same feature

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#839]
Both buttons will open the same "Search / Menu" window. Considering the menu button is shown for both desktop and phone, the search button seems obsolete.
![nav](https://user-images.githubusercontent.com/23152018/31967430-2be70df2-b90e-11e7-9849-298178338a2e.png)

**Comment by ekmartin** [comment]
I think the point was to indicate that there actually is search functionality on Abakus.no now compared to the previous site - but I agree that it might be a bit confusing.

**Comment by SmithPeder** [comment]
Not endorsing this specific icon but a (search/menu) icon could have been used - or some other change
![mobile-menu-icon](https://user-images.githubusercontent.com/23152018/31968259-d85e3b80-b910-11e7-8d39-79c3e024b656.png)
