### ISSUE TITLE
Fix attendancestatus on open events without registration

### ISSUE THREAD

**Issue by odinuge** [webkom/lego-webapp#846]
Make these show something intuitive, instead of just `0/0`. 
![screenshot from 2017-10-26 16-07-15](https://user-images.githubusercontent.com/1467188/32057769-7fa7c6f6-ba68-11e7-9f8f-7f7873b7d456.png)

**Comment by JamiesWhiteShirt** [comment]
Resolved (?) in #1367

**Comment by odinuge** [comment]
Fixed in #1367
