### ISSUE TITLE
Cramped space in on arrangements view in mobile

### ISSUE THREAD

**Issue by cherrybeans** [webkom/lego-webapp#849]
![screenshot_20171026-165834](https://user-images.githubusercontent.com/25204035/32061028-d29fecfa-ba70-11e7-938b-9f87be6df00a.png)

**Comment by odinuge** [comment]
#WeDontSupportAnythingElseThanChrome

The samsung browser has some strange `FlexBox` issues. 

https://github.com/webkom/lego-webapp/blob/master/app/routes/events/components/Toolbar.js#L28
