### ISSUE TITLE
Maybe put in some userinfo in password reset mail

### ISSUE THREAD

**Issue by cherrybeans** [webkom/lego-webapp#850]
Only says "Hei," now, could say e.g. "Hei, Sigrid" 
![screenshot_20171026-141708](https://user-images.githubusercontent.com/25204035/32061145-2de95c9a-ba71-11e7-99f5-24501e031f1b.png)

**Comment by ekmartin** [comment]
If anyone wants to try fixing this:

The password reset email templates are located here:
https://github.com/webkom/lego/blob/master/lego/apps/users/templates/users/email/reset_password.txt
https://github.com/webkom/lego/blob/master/lego/apps/users/templates/users/email/reset_password.html

Variables are available by using e.g. `{{ owner }}`. If you add the user object (retrieved on line 27) [here](https://github.com/webkom/lego/blob/master/lego/apps/users/views/password_reset.py#L34) you can access it in the same way, e.g. `{{ user.full_name }}`.

**Comment by ekmartin** [comment]
Moving this to the backend repository: https://github.com/webkom/lego/issues/953
