### ISSUE TITLE
Put forgot password and register on every login screen

### ISSUE THREAD

**Issue by cherrybeans** [webkom/lego-webapp#851]
Could only find the forgot password on the homepage login right now. Took up some of my time finding it. 
![screenshot_20171026-141242](https://user-images.githubusercontent.com/25204035/32061447-eba0eafa-ba71-11e7-910a-244a3f1d1570.png)

**Comment by odinuge** [comment]
Missing here @SmithPeder? 
![screenshot_20180115-185345](https://user-images.githubusercontent.com/1467188/34955629-9bbf9042-fa25-11e7-8676-52baf7f68bff.png)

**Comment by SmithPeder** [comment]
Yehh, forgot the redirected login page
