### ISSUE TITLE
Tags that cant be replaced with lables

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#871]
This issue is a extensions/result of issue #605

- [ ] EventEditor/index.js
- Cant add a lable to "Påmeldinger", so the `<h3>` tag is still there
![screenshot from 2017-10-27 00-51-29](https://user-images.githubusercontent.com/23152018/32080737-a14ef59c-bab1-11e7-83e1-5e9abb360c8a.png)

- [ ] UserConfirmation,js
- [ ] StudentConfirmation.js
- Some captcha error stopped me from getting a preview of these two pages, but i think they are good

- [ ] MeetingEditor.js
- Since "Møtereferat" is the header to an `editor` it cant be removed
- Same goes for the `AttendanceStatus.Modal`

![screenshot from 2017-10-27 00-39-33](https://user-images.githubusercontent.com/23152018/32080335-52adffb6-baaf-11e7-8031-7830c9715d0e.png)

**Comment by finnss** [comment]
Nicely made issue 👍

**Comment by finnss** [comment]
@SmithPeder Is this fixed?

**Comment by SmithPeder** [comment]
Closing this
