### ISSUE TITLE
[BDB] Show most recent events first

### ISSUE THREAD

**Issue by edvardvb** [webkom/lego-webapp#876]
![image](https://user-images.githubusercontent.com/8725291/32102973-d498b2fe-bb1e-11e7-948f-92af3c696026.png)

Events from 7 years ago might not be very relevant here :)

**Comment by finnss** [comment]
The title makes it feel like `BDB` should be its own issue label, which I'm pretty sure is a bad thing :<

I agree with what you're saying tho, I'll get it fixed.

**Comment by odinuge** [comment]
Isn't this just how the backend sorts events? The lowest `pk` goes first.

**Comment by finnss** [comment]
Nah I do `.sort((a, b) => new Date(b.startTime) - new Date(a.startTime))`. Fixing in an incoming PR.
