### ISSUE TITLE
Too many old meetings are shown

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#882]
Pressing the "Helt Gamle" button on the meeting section displays old meetings. But 99.99% of these are meetings i was never invited to. Do all the meetings appear due to some admin rights or is this how everybody sees it?
![screenshot from 2017-10-27 20-20-36](https://user-images.githubusercontent.com/23152018/32119122-84db8846-bb54-11e7-96a2-20012efe1624.png)

**Comment by finnss** [comment]
This is probably due to admin rights. We talked about the need for meetings to be private even against admins, I don't think there's a consensus or at least a solution yet.

**Comment by SmithPeder** [comment]
If it's due to the admin rights i'll close the issue :100:
