### ISSUE TITLE
Do not render img-tags without a proper `src`

### ISSUE THREAD

**Issue by odinuge** [webkom/lego-webapp#891]
When rendering a picture without a `src` attribute it defaults to `./null`. SSR will then try to render the page, and will most likely do strange things. Most of the times it will timeout, and sometimes it will execute api-calls with an invalid query (`/api/v1/evnets/?company=null`), causing the backend to return a `50X` response. This causes unnecessary computation, and isn't a good practice.

When getting a response from SSR with an image without the `src` tag, the browser will indicate that the page is loading while it is loading as long as the initial requests are running. Since SSR currently have no timeout, the request hits the browsers-timeout (30s in chrome). Resulting in a loading time of `30s`++

Example: https://abakus.no/events/2010

**Comment by larseen** [comment]
This can be solved by using a ProgressiveImage load component as demonstrated here: https://github.com/webkom/lego-webapp/blob/b6ec1955ecdfc60095ca3645bd69b14c8d48d7d6/app/components/ProgressiveImage/index.js

But this need to be tested first, might be disturbing/unnecessary aswell..
