### ISSUE TITLE
Event comment problem

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego-webapp#934]
With the current build a comment like Hafskjold made will wreck the site on mobile
![screenshot_20171103-012553](https://user-images.githubusercontent.com/23152018/32356534-16998f9a-c036-11e7-8599-9a2c91e23fe1.png)
Yeah you can still zoom in, but if you open a modal or something you'll never find it.
![screenshot_20171103-013037](https://user-images.githubusercontent.com/23152018/32356610-ab8aa896-c036-11e7-90b3-8767ef9ea09a.png)
You have to go looking for it... #userexperience
![screenshot_20171103-013048](https://user-images.githubusercontent.com/23152018/32356645-e212b3ae-c036-11e7-8178-66ca92fd8fb9.png)

**Comment by odinuge** [comment]
This was because we removed the outer `<p>  </p>`-tag and rendered the rest as text. Sovled in https://github.com/webkom/lego-webapp/pull/859.

We should not allow infinite deep comment threads as they wreck the UI.
